const fs = require('fs');

let code = fs.readFileSync('src/screens/ChatScreen.tsx', 'utf-8');

// We need to add state for pdfBlobUrl and isGeneratingPDF
code = code.replace(
  "  const messagesEndRef = useRef<HTMLDivElement>(null);",
  "  const messagesEndRef = useRef<HTMLDivElement>(null);\n  const [pdfBlobUrl, setPdfBlobUrl] = useState<string | null>(null);\n  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);\n\n  useEffect(() => {\n    if (messages.some(m => m.type === 'prescription') && !pdfBlobUrl && !isGeneratingPDF) {\n      setIsGeneratingPDF(true);\n      generatePrescriptionPDF(userName, messages, {\n        birthDate: userBirthDate || (answers && answers.birthDate),\n        cpf: userCpf || (answers && answers.cpf),\n        returnBlobUrl: true\n      }).then(url => {\n        if (typeof url === 'string') setPdfBlobUrl(url);\n        setIsGeneratingPDF(false);\n      }).catch(err => {\n        console.error(err);\n        setIsGeneratingPDF(false);\n      });\n    }\n  }, [messages, pdfBlobUrl, isGeneratingPDF, userName, userBirthDate, userCpf, answers]);"
);

code = code.replace(
  "                  <div className=\"flex flex-col gap-3\">\n                    <Button \n                      onClick={() => {\n                        if (msg.attachment) {\n                          const a = document.createElement('a');\n                          a.href = msg.attachment.url;\n                          a.download = msg.attachment.name;\n                          document.body.appendChild(a);\n                          a.click();\n                          document.body.removeChild(a);\n                        } else {\n                          handleGeneratePDF();\n                        }\n                      }} \n                      className=\"w-full bg-mecura-neon text-black hover:bg-[#b5ff33] font-bold shadow-[0_0_20px_rgba(166,255,0,0.25)] rounded-xl h-12\"\n                    >\n                      <Download className=\"w-4 h-4 mr-2\" />\n                      Baixar PDF\n                    </Button>",
  "                  <div className=\"flex flex-col gap-3\">\n                    {msg.attachment ? (\n                      <Button \n                        onClick={() => {\n                          const a = document.createElement('a');\n                          a.href = msg.attachment.url;\n                          a.download = msg.attachment.name;\n                          document.body.appendChild(a);\n                          a.click();\n                          document.body.removeChild(a);\n                        }} \n                        className=\"w-full bg-mecura-neon text-black hover:bg-[#b5ff33] font-bold shadow-[0_0_20px_rgba(166,255,0,0.25)] rounded-xl h-12\"\n                      >\n                        <Download className=\"w-4 h-4 mr-2\" />\n                        Baixar PDF\n                      </Button>\n                    ) : (\n                      <a\n                        href={pdfBlobUrl || '#'}\n                        download={`Receita_${userName || 'Paciente'}.pdf`}\n                        onClick={(e) => {\n                           if (!pdfBlobUrl) {\n                             e.preventDefault();\n                             if (!isGeneratingPDF) handleGeneratePDF();\n                           }\n                        }}\n                        className={`w-full flex items-center justify-center bg-mecura-neon text-black font-bold shadow-[0_0_20px_rgba(166,255,0,0.25)] rounded-xl h-12 ${!pdfBlobUrl ? 'opacity-70 cursor-wait' : 'hover:bg-[#b5ff33]'}`}\n                      >\n                        {isGeneratingPDF ? (\n                          <span className=\"flex items-center gap-2\">\n                            <div className=\"w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin\" />\n                            Gerando PDF...\n                          </span>\n                        ) : (\n                          <span className=\"flex items-center gap-2\">\n                            <Download className=\"w-4 h-4\" /> Baixar PDF\n                          </span>\n                        )}\n                      </a>\n                    )}"
);

fs.writeFileSync('src/screens/ChatScreen.tsx', code);
